services:
  server:
    build:
      context: .
      target: runtime
    ports:
      - '8080:8080'
    environment:
      - 'APP_ENV=stg'
      - 'HOST=0.0.0.0:8080'
      - 'DB_READ_POOL_CONN_STR=postgresql://postgres:pass@db'
      - 'DB_WRITE_POOL_CONN_STR=postgresql://postgres:pass@db'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_PASSWORD=pass' # can connect with postgres:pass
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresql_data:
    driver: local
