services:
  pgsql:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_PASSWORD=pass' # can connect with postgres:pass

volumes:
  postgresql_data:
    driver: local
