name: coverage

on: [push]
jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate code coverage
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            summary=$(cargo +nightly tarpaulin --timeout 120 --out StdOut);
            const body = ${summary};
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
