name: coverage

on: [push]
jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate code coverage
        id: cov
        run: |
          summary = $(cargo +nightly tarpaulin --timeout 120 --out StdOut)
          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## Coverage summary >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```bash' >> $GITHUB_OUTPUT
          echo "$summary" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      - name: Paste Comment
        uses: actions/github-script@v7
        env:
          SUMMARY: "${{ steps.cov.outputs.summary }}"
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const body = `${SUMMARY}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
